/**
 * Names that identify an agent as test residue.
 *
 * Kept in its own module, free of side effects, so the guard test can import it
 * without running the prune script (which needs service-role credentials and
 * exits when they are absent).
 *
 * Deliberately specific rather than clever. A pattern like /test/ would match a
 * real agent working on a project called "tests", and the cost of a false
 * positive here is a working agent that silently stops receiving messages.
 *
 * ⚠️ A pattern here must NOT match a name the test suites still register.
 *
 * The original list did, and it broke the build. Residue accumulated because
 * suites suffixed agent names with `Date.now()`, so every run created new rows.
 * Fixing that made the names *fixed* — which turned them from disposable
 * residue into the suites' permanent identities. Running the prune then
 * deactivated the identities the integration tier authenticates with, and the
 * whole tier failed 401 on the next deploy.
 *
 * `packages/shared/src/__tests__/residue-patterns.test.ts` reads the agent
 * names out of the integration sources and asserts no pattern below matches
 * one, so this cannot regress silently again.
 */
export const RESIDUE_PATTERNS: Array<{ pattern: RegExp; source: string }> = [
  // Historic residue only: names generated by code that no longer runs, or by
  // one-off manual verification. None of these are registered by a live suite.
  { pattern: /^macbook-agent-[0-9a-f]{8}$/, source: 'generated fixture (pre-fix dynamic name)' },
  { pattern: /-(verify|verify\d)-claude-ai$/, source: 'connector verification (manual, one-off)' },
  { pattern: /^macbook-dmtest-/, source: 'DM matrix verification (manual, one-off)' },
  { pattern: /^macbook-(fakeproj|proj-[ab])$/, source: 'cooldown verification (manual, one-off)' },
  { pattern: /^supernode-admin-setup-at-/, source: 'supernode setup fixture' },
];

// Deliberately NOT matched, despite looking like probes:
//
//   macbook-shapeprobe  — follows the {machine}-{project} convention exactly,
//                         which is what a real agent looks like. Any Claude
//                         Code session in a directory named "shapeprobe"
//                         registers as this, possibly on another machine.
//
// The rule: if a name is indistinguishable from {machine}-{project}, leave it.
// A stale row costs a line in a list; a wrongly deactivated agent stops
// receiving messages and gives no clue why.

export function residueSource(name: string): string | null {
  for (const { pattern, source } of RESIDUE_PATTERNS) {
    if (pattern.test(name)) return source;
  }
  return null;
}
